apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox-1
spec:
  volumes:
    - name: log-volume
      emptyDir: {}
  containers:
    - image: busybox
      name: busybox-1
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh"]
      args: ["-c","while true; do date > /var/output/log.txt; sleep 5;done"]
      volumeMounts:
        - name: log-volume
          mountPath: /var/output