apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox-2
spec:
  volumes:
    - name: log-volume
      hostPath:
        path: /var/output
  containers:
    - image: busybox
      name: busybox-2
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh"]
      args: ["-c","while true; do date >> /var/output/log.txt; sleep 5;done"]
      volumeMounts:
        - name: log-volume
          mountPath: /var/output