apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-brixton
  namespace: brixton
spec:
  storageClassName: database
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteMany
