apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    imagePullPolicy: IfNotPresent
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
    livenessProbe:
      exec:
        command:
          - cat
          - /usr/share/nginx/html/index.html
      periodSeconds: 10