apiVersion: v1
kind: Pod
metadata:
  labels:
    run: alpine
  name: alpine
spec:
  securityContext:
    runAsUser: 45
    runAsGroup: 231
  volumes:
    - name: log-date-vol
      emptyDir: {}
  containers:
  - image: alpine
    name: alpine
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /etc/kal-directory/date-file.txt; sleep 5; done"]
    volumeMounts:
      - name: log-date-vol
        mountPath: /etc/kal-directory