apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-container-pod
  name: multi-container-pod
spec:
  volumes:
    - name: shared-vol
      emptyDir: {}
  containers:
    - image: ubuntu
      name: ubuntu
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh"]
      args: ["-c", "while true; do ps aux --sort=-pmem > /logs/output.txt; sleep 10; done"]
      volumeMounts:
        - name: shared-vol
          mountPath: /logs
    - image: alpine
      name: alpine
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh"]
      args: ["-c", "while true; do date > /logs/report.txt; cat /logs/output.txt | head -4 >> /logs/report.txt; sleep 10; done"]
      volumeMounts:
        - name: shared-vol
          mountPath: /logs