apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
    - image: busybox
      name: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh"]
      args: ["-c","while true;do echo 'Hello from pages Yellow Pages';sleep 10;done"]