apiVersion: v1
kind: Pod
metadata:
  annotations:
    team: yourteam
    course: k8s
  labels:
    run: nginx
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      imagePullPolicy: IfNotPresent